cd_app/authenticate/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.security import check_password_hash

from .forms import userForm, LoginForm
from cd_app.models import User

from flask_login import login_user, logout_user,login_required,current_user

auth = Blueprint('authenticate',__name__,template_folder='auth_templates')

from cd_app.models import db

@auth.route('/login', methods=['GET','POST'])
def logIn():
    log_form = LoginForm()
    if request.method == 'POST' and log_form.validate():
        email = log_form.email.data
        password = log_form.password.data 
        remember_me = log_form.remember_me.data

        user = User.query.filter_by(email=email).first()

        if user is None or not check_password_hash(user.password, password):
            return redirect(url_for('authenticate.logIn'))

        login_user(user,remember=remember_me)
        print(current_user)
        return redirect(url_for('homePage'))


    return render_template('log_in.html', form=log_form, title='Log In')

@auth.route('/signup', methods=["POST","GET"])
def signUp():
    auth_form = userForm()
    if request.method == 'POST':
        if auth_form.validate():
            first = auth_form.first_name.data
            last = auth_form.last_name.data
            email = auth_form.email.data
            password = auth_form.password.data

            new_user = User(first,last,email,password)

            db.session.add(new_user)
            db.session.commit()
            
            return redirect(url_for('homePage'))
            
    return render_template('sign_up.html', form=auth_form, title='Sign Up')

@auth.route('/logout')
def logOut():
    logout_user()
    return redirect(url_for('authenticate.logIn'))

cd_app/inventory/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user, login_required

from .forms import addToInventory, removeInventory, updateListingForm

from cd_app.models import Inventory, Reserve

inv  = Blueprint('inventory', __name__, template_folder='inv_templates')

from cd_app.models import db

import requests as r

@inv.route('/inventory')
def inventory_page():
    inventory = Inventory.query.all()
    if inventory == None:
        return render_template('add_to.html')
    return render_template('data_list.html', inventory=inventory, current=current_user.id, title='Inventory Listing')

@inv.route('/inventory/chucknorris_add')
def chuckJokes_add():
    api= r.get('https://api.chucknorris.io/jokes/random')
    the_jokes = api.json()
    jokes = the_jokes['value']
    return render_template('add_chuckjokes.html', jokes=jokes)

@inv.route('/inventory/chucknorris_remove')
def chuckJokes_remove():
    api= r.get('https://api.chucknorris.io/jokes/random')
    the_jokes = api.json()
    jokes = the_jokes['value']
    return render_template('remove_chuckjokes.html', jokes=jokes)

@inv.route('/inventory/add_to_inventory', methods=['GET','POST'])
def addInv():
    add_form = addToInventory()
    if request.method == 'POST':
        if add_form.validate():

            image = add_form.image.data
            vin_num = add_form.vin_num.data
            year = add_form.year.data
            make = add_form.make.data
            model = add_form.model.data
            description = add_form.description.data

            item = Inventory(image,vin_num,year,make,model,description,current_user.id)
            db.session.add(item)
            db.session.commit()
            swap = Reserve(image,vin_num,year,make,model,description)
            db.session.add(swap)
            db.session.commit()

            return redirect(url_for('inventory.chuckJokes_add'))
    return render_template('add_to.html',form=add_form, title='Add To Inventory')

@inv.route('/inventory/item_remove', methods = ['GET','POST'])
@login_required
def removeInv():
    remove_form=removeInventory()
    id = remove_form.id.data
    item=Inventory.query.filter_by(id=id).first()


    if request.method == 'POST':
        if remove_form.validate():

            if item.user_id != current_user.id:
                return render_template('remove.html',form=remove_form,title='Remove From Inventory')

            db.session.delete(item)
            db.session.commit()

            return redirect(url_for('inventory.chuckJokes_remove'))
    return render_template('remove.html',form=remove_form,title='Remove From Inventory')

@inv.route('/inventory/retrieve')
@login_required
def retrieveReserve():
    rr=Reserve.query.all()
    return render_template('retrieve.html',rr=rr,title='Reserve Database')

@inv.route('/inventory/reserve_vehicle<int:id>')
@login_required
def vehicleListingPage(id):
    vehicle = Reserve.query.filter_by(id=id).first()
    if vehicle is None:
        return redirect(url_for('inventory.retrieveReserve'))
    return render_template('reserve_vehicle.html', v=vehicle)

@inv.route('/inventory/my_vehicle/<int:id>')
@login_required
def myVehiclePage(id):
    vehicle1 = Inventory.query.filter_by(id=id).first()

    return render_template('my_vehicle.html', v=vehicle1)

@inv.route('/inventory/retrieve/<int:id>', methods=["GET","POST"])
@login_required
def retrieveReserveListing(id):
    listing=Reserve.query.filter_by(id=id).first()

    retrieve=Inventory(listing.image,listing.vin_num,listing.year,listing.make,listing.model,listing.description,current_user.id)

    db.session.add(retrieve)
    db.session.commit()
    return redirect(url_for('inventory.chuckJokes_add'))

@inv.route('/inventory/update/<int:id>', methods=['GET','POST'])
@login_required
def updateListing(id):
    update_form=updateListingForm()
    listing=Inventory.query.filter_by(id=id).first()

    if request.method == 'POST':
        if update_form.validate():

            image = update_form.image.data
            vin_num = update_form.vin_num.data
            year = update_form.year.data
            make = update_form.make.data
            model = update_form.model.data
            description = update_form.description.data

            if not image:
                image=listing.image
            if not vin_num:
                vin_num=listing.vin_num
            if not year:
                year=listing.year
            if not make:
                make=listing.make
            if not model:
                model=listing.model
            if not description:
                description=listing.description
                
            listing.image=image
            listing.vin_num=vin_num
            listing.year=year
            listing.make=make
            listing.model=model
            listing.description=description
            db.session.commit()

            return redirect(url_for('inventory.myVehiclePage', id=id))
    return render_template('update.html', form=update_form, title='Update Listing')

cd_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-decoration-underline">This is the about page</h1>
    <h3>Content to follow.....</h3>
    
{% endblock content %}

cd_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<link rel='stylesheet' href={{ url_for('static',filename='/css/signup.css')  }}>
<title>{{title}}</title>
</head>
<body>

        {% include 'nav.html' %}

<main class='container'>
        {% block content %}

        {% endblock content %}
</main>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

cd_app/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<link rel='stylesheet' href={{ url_for('static',filename='/css/signup.css')  }}>
<title>{{title}}</title>
</head>
<body>

        {% include 'nav2.html' %}

<main class='container'>
        {% block content %}

        {% endblock content %}
</main>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

cd_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-decoration-underline">This is the home page</h1>
    <h3>Content to follow.....</h3>
{% endblock content %}

cd_app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <a class="navbar-brand" href="#">The Car Collection</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('aboutPage') }}">about</a>
              </li>


              {% if current_user.is_authenticated %}
              
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('inventory.inventory_page') }}">Check Inventory</a>
              </li>
              <li class="nav-item">
                  <p class="nav-link" >Welcome, {{ current_user.first_name }}</p>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('authenticate.logOut') }}">Log Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ url_for('authenticate.logIn') }}">Log In</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ url_for('authenticate.signUp') }}">Sign Up</a>
              </li>

              {% endif %}







          </ul>
          <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
      </div>
  </div>
</nav>

cd_app/templates/nav2.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">The Car Collection</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('aboutPage') }}">about</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Inventory Menu
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ url_for('inventory.addInv') }}">Add To Inventory</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('inventory.removeInv') }}">Remove From Inventory</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{{ url_for('inventory.retrieveReserve') }}">Retrieve Reserve Listing</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <p class="nav-link" >Welcome, {{ current_user.first_name }}</p>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('authenticate.logOut') }}">Log Out</a>
                </li>

            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
  </nav>